routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\User\HomeController::class, 'index'])->name('user.home');

Route::get('/post/{post}', [\App\Http\Controllers\User\HomeController::class, 'show'])->name('user.post');
Route::get('/category/{category}', [\App\Http\Controllers\User\HomeController::class, 'showCategory'])->name('user.showCategory');


Route::get('/manager', [HomeController::class, 'index'])->name('admin.home');
Route::resource('/manager/posts', PostController::class);
Route::resource('/manager/categories', CategoryController::class);

app/Models/User/Category.php
<?php

namespace App\Models\User;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title'];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Validation\ValidationException;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {

        return view('admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'title' => 'required',
        ]);
        Category::create($validatedData);

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Category $category
     * @return Application|RedirectResponse|Redirector
     * @throws ValidationException
     */
    public function update(Request $request, Category $category)
    {
        $validatedData = $this->validate($request, [
            'title' => 'required',
        ]);
        $category->update($validatedData);

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return RedirectResponse
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->back();
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.app')

@section('admin-content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Category</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="{{ route('categories.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="offset-3 col-6">
                        <div class="form-group">
                            <label for="title">Category Title</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title" autofocus value="{{ old('title') }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a class="btn btn-warning" href="{{ route('categories.index') }}">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.app')

@section('admin-content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit Category</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="{{ route('categories.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="offset-3 col-6">
                        <div class="form-group">
                            <label for="title">Category Title</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title" autofocus value="{{ $category->title }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a class="btn btn-warning" href="{{ route('categories.index') }}">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('admin-content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Categories</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title p-2">Category</h3>
                <a class="offset-5 btn btn-outline-success" href="{{ route('categories.create') }}">Add New</a>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i></button>
                </div>
            </div>
            <div class="card-body">
                <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>ID ##</th>
                                <th>Category Title</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->title }}</td>
                                <td><a href="{{ route('categories.edit', $category) }}"><i class="fas fa-edit text-success"></i></a></td>
                                <td>
                                    <form id="deleteForm-{{ $category->id }}" action="{{ route('categories.destroy', $category) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <a href="" onclick="
                                            if(confirm('Are you sure to delete this category?')){
                                            event.preventDefault();
                                            document.getElementById('deleteForm-{{ $category->id }}').submit();
                                            } else{
                                            event.preventDefault();
                                            }
                                            ">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>ID ##</th>
                                <th>Category Title</th>

                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('admin-footer')
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@endsection