routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\User\HomeController::class, 'index'])->name('user.home');

Route::get('/post/{post}', [\App\Http\Controllers\User\HomeController::class, 'show'])->name('user.post');
Route::get('/category/{category}', [\App\Http\Controllers\User\HomeController::class, 'showCategory'])->name('user.showCategory');


Route::get('/manager', [HomeController::class, 'index'])->name('admin.home');
Route::resource('/manager/posts', PostController::class);
Route::resource('/manager/categories', CategoryController::class);

app/Models/User/Post.php
<?php

namespace App\Models\User;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'sub_title', 'body', 'category_id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User\Category;
use App\Models\User\Post;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $posts = Post::all();
        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Application|RedirectResponse|Redirector
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'title' => 'required',
            'sub_title' => 'required',
            'body' => 'required',
            'category_id' => 'required|numeric',
        ]);
        Post::create($validatedData);
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return Application|Factory|View
     */
    public function edit(Post $post)
    {
        return view('admin.post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Post $post
     * @return Application|RedirectResponse|Redirector
     * @throws ValidationException
     */
    public function update(Request $request, Post $post)
    {
        $validatedData = $this->validate($request, [
            'title' => 'required',
            'sub_title' => 'required',
            'body' => 'required',
            'category_id' => 'required|numeric',
        ]);
        $post->update($validatedData);
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Post $post
     * @return RedirectResponse
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->back();
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('admin-content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Post</h3>
        </div>
        @if(count($errors) > 0)
            @foreach($errors->all() as $error)
                <p class="alert alert-danger">{{ $error }}</p>
            @endforeach
        @endif
        <form role="form" action="{{ route('posts.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="row">
                        <div class="form-group col-4">
                            <label for="title">Post Title</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title" value="{{ old('title') }}">
                        </div>
                        <div class="form-group col-4">
                            <label for="sub_title">Post Sub Title</label>
                            <input type="text" class="form-control" id="sub_title" name="sub_title"
                                   placeholder="Enter Sub title" value="{{ old('sub_title') }}">
                        </div>
                        <div class="form-group col-4">
                            <label for="category_id">Post Sub Title</label>
                            <select class="form-control" name="category_id" id="category_id">
                                <option selected disabled>Select the category</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                <div class="mb-3">
                    <textarea class="textarea" placeholder="Place some text here" name="body" rows="20" style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ old('body') }}</textarea>
                </div>
            </div>


            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('posts.index') }}" class="btn btn-warning">Back</a>
            </div>
        </form>
    </div>
@endsection

@section('admin-footer')

    <!-- AdminLTE for demo purposes -->
{{--    <script src="{{ asset('../../dist/js/demo.js') }}"></script>--}}
    <!-- Summernote -->
    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>
        $(function () {
            // Summernote
            $('.textarea').summernote()
        })
    </script>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')

@section('admin-head')
    <link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('admin-content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit Post</h3>
        </div>
        @if(count($errors) > 0)
            @foreach($errors->all() as $error)
                <p class="alert alert-danger">{{ $error }}</p>
            @endforeach
        @endif
        <form role="form" action="{{ route('posts.update', $post) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="row">
                        <div class="form-group col-4">
                            <label for="title">Post Title</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title" value="{{ $post->title }}">
                        </div>
                        <div class="form-group col-4">
                            <label for="sub_title">Post Sub Title</label>
                            <input type="text" class="form-control" id="sub_title" name="sub_title"
                                   placeholder="Enter Sub title" value="{{ $post->sub_title }}">
                        </div>
                        <div class="form-group col-4">
                            <label for="category_id">Post Sub Title</label>
                            <select class="form-control" name="category_id" id="category_id">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}" @if($category->id == $post->category_id) selected @endif>{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                <div class="mb-3">
                    <textarea class="textarea" placeholder="Place some text here" name="body" rows="20" style="width: 100%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $post->body }}</textarea>
                </div>
            </div>


            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('posts.index') }}" class="btn btn-warning">Back</a>
            </div>
        </form>
    </div>
@endsection

@section('admin-footer')

    <!-- AdminLTE for demo purposes -->
{{--    <script src="{{ asset('../../dist/js/demo.js') }}"></script>--}}
    <!-- Summernote -->
    <script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>
        $(function () {
            // Summernote
            $('.textarea').summernote()
        })
    </script>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.layouts.app')

@section('admin-content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Blank Page</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Post</h3>
                <a class="offset-5 btn btn-outline-success" href="{{ route('posts.create') }}">Add New</a>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i></button>
                </div>
            </div>
            <div class="card-body">
                <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>ID ##</th>
                                <th>Post Title</th>
                                <th>Post Category</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ $post->category->title }}</td>
                                    <td><a href="{{ route('posts.edit', $post) }}"><i class="fas fa-edit"></i></a></td>
                                    <td>
                                        <form id="delete-form-{{ $loop->iteration }}" action="{{ route('posts.destroy', $post) }}" method="POST" >
                                            @csrf
                                            @method('DELETE')
                                            <a href="" onclick="
                                                if(confirm('Are you sure to delete this?')){
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{ $loop->iteration }}').submit();
                                                } else{
                                                    event.preventDefault();
                                                  }
                                                ">

                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>ID ##</th>
                                <th>Post Title</th>
                                <th>Post Category</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
@endsection